# apiVersion: v1
# kind: Secret
# metadata:
#   name: auth-mongo-creds
# type: Opaque
# data:
#   password: cGFzc3dvcmQxMjM= #password123
#   username: YWRtaW51c2Vy #adminuser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
      - name: auth-mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: auth-mongo-creds
        #       key: username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: auth-mongo-creds
        #       key: password        
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - name: monogodb
          protocol: TCP
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-service
  labels:
    app: auth-mongo
spec:
  selector:
    app: auth-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-external-service
spec:
  type: NodePort
  selector:
    app: auth-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    # targetPort: 27017
    nodePort: 30001
