apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: bsatyadeep/expiration
        imagePullPolicy: Never
        env:
          - name: NATS_URI
            value: http://nats-service:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REDIS_HOST
            value: expiration-redis-service
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-service
# spec:
#   selector:
#     app: expiration
#   ports:
#   - name: expiration
#     protocol: TCP
#     port: 3000
#     targetPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-external-service
# spec:
#   type: NodePort
#   selector:
#     app: expiration
#   ports:
#   - name: expiration
#     protocol: TCP
#     port: 3000
#     targetPort: 3000
