apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
      - name: expiration-redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: redisdb
          protocol: TCP
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-service
  labels:
    app: expiration-redis
spec:
  selector:
    app: expiration-redis
  ports:
  - name: redisdb
    protocol: TCP
    port: 6379
    targetPort: 6379
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-redis-external-service
# spec:
#   type: NodePort
#   selector:
#     app: expiration-redis
#   ports:
#   - name: redisdb
#     protocol: TCP
#     port: 6379
#     targetPort: 6379
#     nodePort: 32583
