apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
      - name: orders-mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: monogodb
          protocol: TCP
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-service
  labels:
    app: orders-mongo
spec:
  selector:
    app: orders-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-external-service
spec:
  type: NodePort
  selector:
    app: orders-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    # targetPort: 27017
    nodePort: 30003
