apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: bsatyadeep/payments
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            value: 'mongodb://payments-mongo-service:27017/payments'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_URI
            value: http://nats-service:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-secret
                key: STRIPE_KEY
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
  - name: payments
    protocol: TCP
    port: 3000
    targetPort: 3000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: payments-external-service
# spec:
#   type: NodePort
#   selector:
#     app: payments
#   ports:
#   - name: payments
#     protocol: TCP
#     port: 3000
#     targetPort: 3000
