apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
      - name: tickets-mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: monogodb
          protocol: TCP
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-service
  labels:
    app: tickets-mongo
spec:
  selector:
    app: tickets-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-external-service
spec:
  type: NodePort
  selector:
    app: tickets-mongo
  ports:
  - name: monogodb
    protocol: TCP
    port: 27017
    # targetPort: 27017
    nodePort: 30002
