apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: bsatyadeep/tickets
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-service:27017/tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_URI
            value: http://nats-service:4222
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tickets-external-service
# spec:
#   type: NodePort
#   selector:
#     app: tickets
#   ports:
#   - name: tickets
#     protocol: TCP
#     port: 3000
#     targetPort: 3000
